on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start workflow message
      run: echo "Now running build workflow."

    - name: Ending workflow message
      run: |
        echo "Build workflow complete."
        echo "Ready to add, test, and deploy your project."
